# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    sciAdmin:
                        password: e=mc2
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            # http_basic: ~

            # Active la prise en charge de notre formulaire de login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: app_login
                check_path: app_login

            # Active le logout (ne fonctionne pas avec http_basic)
            logout:
                path:   /logout
                target: app_login

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
