AppBundle/Entity/Publication:
    properties:
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~
        content:
            - NotBlank: ~
        author:
            - NotBlank: ~
        science:
            - NotBlank: ~